
import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eskor
 */
public class JFrameGUIdames extends javax.swing.JFrame {
    
    boolean jugaX = true;
    boolean jugaO = false;
    int filaOrigen = -1;
    int columnaOrigen = -1;
    /**
     * Creates new form JFrameGUIdames
     */
    public JFrameGUIdames() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Sortir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"X", "", "X", null, "X", null, "X", null},
                {"", "X", "", "X", null, "X", null, "X"},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, "", null, null, null, null, null, null},
                {"O", null, "O", null, "O", null, "O", null},
                {"", "O", null, "O", null, "O", null, "O"}
            },
            new String [] {
                "Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(204, 204, 204))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Tanca el programa
        System.exit(0);
    
    }//GEN-LAST:event_jButton1ActionPerformed

//METODES
    
    //Comrova si la casella es X
    public boolean esX (int fila, int columna){
        if (jTable2.getValueAt(fila, columna) == "X"){
            return true;
        } else {
            return false;
        }
    }
    
    //Comprova si la casella es O
    public boolean esO (int fila, int columna){
        if (jTable2.getValueAt(fila, columna) == "O"){
            return true;
        } else {
            return false;
        }
     }
    
    //Obte la fila
    public int obtenirFilaClicada (){
        int fila = jTable2.getSelectedRow();
        
        return fila;
    }
    
    //Obte la columna
    public int obtenirColumnaClicada (){
        int columna = jTable2.getSelectedColumn();
        
        return columna;
    }
    
    public boolean noHiHaOrigen(){
        if(filaOrigen == -1 && columnaOrigen == -1){
            return true;
        } else {
            return false;
        }
    }
    
    public void actualitzaNouOrigen(int fila, int columna){
        filaOrigen = obtenirFilaClicada();
        columnaOrigen = obtenirColumnaClicada();
                
    }
            
    public void mostraError(){
        System.out.println("Error");
    }
    
    public boolean movimentValid(int fila, int columna){
        return true;
    }
    
    //Comprova si hi ha una casella buida, retorna true si esta buida retorna false si esta plena
    public boolean esBuit(int fila, int columna){
        if(jTable2.getValueAt(fila, columna) == null){
            return true;
        } else {
            return false;
        }        
    }
    
    //Comprova si la casella esta ocupada per ficha contraria
    public boolean ocupatContrari(int fila, int columna){
        if(jugaX && jTable2.getValueAt(fila, columna) == "O"){
            return true;
        } else if (jugaO && jTable2.getValueAt(fila, columna) == "X"){
            return true;
        } else {
            return false;
        }
    }
    
    public void mou(int fila, int columna){
        if(jugaO){
            jTable2.setValueAt("X", fila, columna);
            
        } else if (jugaX){
            jTable2.setValueAt("O", fila, columna);
        }
        
    }
    
    //Comprova si la casella esta ocupada per una ficha igual a la seva
    public boolean ocupatPropi(int fila, int columna){
        if(jugaX && jTable2.getValueAt(fila, columna) == "X"){
            return true;
        } else if (jugaO && jTable2.getValueAt(fila, columna) == "O"){
            return true;
        } else {
            return false;
        }
    }
            
    public void mostraErrorMoviment(){
        System.out.println("Error de moviment");
    }
        
    public JFrameGUIdames(JButton jButton1, JScrollPane jScrollPane2, JTable jTable2) throws HeadlessException {
        this.jButton1 = jButton1;
        this.jScrollPane2 = jScrollPane2;
        this.jTable2 = jTable2;
    }

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        
        //Inicialització:
        int fila = obtenirFilaClicada();
        int columna = obtenirColumnaClicada();
                
        if(noHiHaOrigen()){
            if (jugaX && esX(fila, columna)){
                actualitzaNouOrigen(fila, columna);
            }else if(jugaO && esO(fila, columna)){
                actualitzaNouOrigen(fila, columna);
            } else {
                mostraError();
            }
            
        } else {
            if (movimentValid(fila, columna)){
                         
                if(esBuit(fila, columna) || ocupatContrari(fila, columna)){
                    mou(fila, columna);
                }
                
            } else if (ocupatPropi(fila, columna)){
                actualitzaNouOrigen(fila, columna);
                
            } else {
                mostraErrorMoviment();
            }
        }
    
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGUIdames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGUIdames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGUIdames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGUIdames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGUIdames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
